project:
  type: website
  preview:
    port: 4200
website:
  title: '‚ü≤ francojc'
  favicon: 'assets/images/favicon.png'
  # google-analytics: 'G-C6T0ESR1RW'
  site-url: https://francojc.github.io/
  search:
    location: navbar
    type: textbox
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
  navbar:
    background: dark
    left:
      - text: 'Home'
        file: index.qmd
      - posts.qmd
      - text: 'Vitae'
        file: cv.qmd
  page-footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
    <img alt="Creative Commons License" style="border-width:0"
    src="https://i.creativecommons.org/l/by/4.0/80x15.png"></a>
    Jerid Francom
format:
  html:
    include-in-header: assets/js/analytics.js
    theme: journal
    fontsize: 1.1em
    css: assets/css/styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
